//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmashZone.Pages.User
{
    public partial class tennisProducts
    {
        protected global::System.Web.UI.WebControls.Label lblProductCount;
        protected global::System.Web.UI.WebControls.Repeater rptProducts;
    }
}
